INSERT into university(uni_id, name_of_university, address, specialization) values (2, 'KPI', 'peremohy 30 str.', 'technical');
INSERT into university(uni_id, name_of_university, address, specialization) values (3, 'KPI', 'peremohy 30 str.', 'technical');
INSERT into university(uni_id, name_of_university, address, specialization) values (4, 'KPI', 'peremohy 30 str.', 'technical');
INSERT into university(uni_id, name_of_university, address, specialization) values (5, 'KPI', 'peremohy 30 str.', 'technical');
INSERT into student(student_id, first_name, last_name, address, student_card_number) values (2, 'John', 'Shepard', 'Lvivska 4 str','423541646' );
INSERT into student(student_id, first_name, last_name, address, student_card_number) values (3, 'John', 'Shepard', 'Lvivska 4 str','423541646' );
INSERT into student(student_id, first_name, last_name, address, student_card_number) values (4, 'John', 'Shepard', 'Lvivska 4 str','423541646' );
INSERT into student(student_id, first_name, last_name, address, student_card_number) values (5, 'John', 'Shepard', 'Lvivska 4 str','423541646' );
INSERT into subject(subject_id, name, description, valid, date_of_creation) values (2, 'Math', 'Science about count', true, TO_DATE('12/05/2000', 'DD/MM/YYYY'));
INSERT into subject(subject_id, name, description, valid, date_of_creation) values (3, 'Math', 'Science about count', true, TO_DATE('12/05/2000', 'DD/MM/YYYY'));
INSERT into subject(subject_id, name, description, valid, date_of_creation) values (4, 'Math', 'Science about count', true, TO_DATE('12/05/2000', 'DD/MM/YYYY'));
INSERT into subject(subject_id, name, description, valid, date_of_creation) values (5, 'Math', 'Science about count', true, TO_DATE('12/05/2000', 'DD/MM/YYYY'));