CREATE TABLE customer(
                id int(10) PRIMARY KEY NOT NULL,
                name VARCHAR(64) NOT NULL,
                surname VARCHAR(128) NOT NULL,
                date_of_birth DATE NOT NULL,
                phone_number VARCHAR(24),
                available_funds DECIMAL(15,2) DEFAULT 0);

CREATE TABLE AUTO(
  ID int(11) NOT NULL AUTO_INCREMENT,
  AUTO_BRAND VARCHAR(20) NOT NULL,
  AUTO_MODEL VARCHAR(20) NOT NULL,
  MANUFACT_YEAR INT(4) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL ,
  PRICE DECIMAL NOT NULL ,
  PRIMARY KEY (ID)
);

insert into AUTO(ID, AUTO_BRAND, AUTO_MODEL, MANUFACT_YEAR, COUNTRY, PRICE)values(1,'BMW', 'X1', 2012, 'Germany', 100000);
insert into AUTO(ID, AUTO_BRAND, AUTO_MODEL, MANUFACT_YEAR, COUNTRY, PRICE)values(2, 'BMW', 'X3', 2013, 'Germany', 200000);
insert into AUTO(ID, AUTO_BRAND, AUTO_MODEL, MANUFACT_YEAR, COUNTRY, PRICE)values(3, 'BMW', 'X4', 2014, 'Germany', 300000);
insert into AUTO(ID, AUTO_BRAND, AUTO_MODEL, MANUFACT_YEAR, COUNTRY, PRICE)values(4, 'BMW', 'X5', 2015, 'Germany', 400000);
insert into AUTO(ID, AUTO_BRAND, AUTO_MODEL, MANUFACT_YEAR, COUNTRY, PRICE)values(5, 'BMW', 'X6', 2016, 'Germany', 500000);
